### ISSUE TITLE
don't cache development builds

### ISSUE THREAD

**Issue by littledivy** [denoland/deno_bindgen#57]
I have to `rm -rf  ~/Library/Caches/deno/plug/` after every rebuild to keep the cache up to date. We should just disable caching local plugins.

**Comment by mwcz** [comment]
I stumbled into this problem today, trying to figure out why my rust changes weren't showing up.  The thing is, for the crates I'm building, I always run in release mode even during development because the crates I'm working with are painfully slow without optimizations.

In addition to not caching development builds, what would you think of having an option to disable caching even for release builds?

**Comment by littledivy** [comment]
@mwcz I agree on disabling cache by default for all local builds (including `--release`). It doesn't really makes sense to cache it :-)
